package technology.polygon.omswallet.docs

import org.jetbrains.kotlin.cli.jvm.compiler.EnvironmentConfigFiles
import org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment
import org.jetbrains.kotlin.com.intellij.openapi.Disposable
import org.jetbrains.kotlin.com.intellij.openapi.util.Disposer
import org.jetbrains.kotlin.com.intellij.psi.PsiErrorElement
import org.jetbrains.kotlin.com.intellij.psi.util.PsiTreeUtil
import org.jetbrains.kotlin.config.CommonConfigurationKeys
import org.jetbrains.kotlin.config.CompilerConfiguration
import org.jetbrains.kotlin.kdoc.psi.api.KDoc
import org.jetbrains.kotlin.kdoc.psi.impl.KDocLink
import org.jetbrains.kotlin.lexer.KtTokens
import org.jetbrains.kotlin.psi.KtClass
import org.jetbrains.kotlin.psi.KtClassInitializer
import org.jetbrains.kotlin.psi.KtClassOrObject
import org.jetbrains.kotlin.psi.KtDeclaration
import org.jetbrains.kotlin.psi.KtEnumEntry
import org.jetbrains.kotlin.psi.KtFile
import org.jetbrains.kotlin.psi.KtNamedDeclaration
import org.jetbrains.kotlin.psi.KtNamedFunction
import org.jetbrains.kotlin.psi.KtObjectDeclaration
import org.jetbrains.kotlin.psi.KtParameter
import org.jetbrains.kotlin.psi.KtPrimaryConstructor
import org.jetbrains.kotlin.psi.KtProperty
import org.jetbrains.kotlin.psi.KtPsiFactory
import org.jetbrains.kotlin.psi.KtSecondaryConstructor
import org.jetbrains.kotlin.psi.KtSuperTypeCallEntry
import org.jetbrains.kotlin.psi.KtTypeAlias
import java.io.File

internal const val GENERATED_MARKER =
    "<!-- Generated by tools/api-docs-generator/src/main/kotlin/technology/polygon/omswallet/docs/ApiDocsGenerator.kt. Do not edit directly. -->"

internal val requiredGroups =
    listOf(
        "OMSWallet",
        "Authentication and sessions",
        "Transactions and signing",
        "Indexer",
        "Networks, types, and errors",
    )

private val splitMemberOwners =
    setOf(
        "technology.polygon.omswallet.wallet.WalletClient",
        "technology.polygon.omswallet.indexer.IndexerClient",
    )

internal data class ApiSymbol(
    val id: String,
    val declarations: MutableList<ApiDeclaration> = mutableListOf(),
)

internal data class ApiDeclaration(
    val signature: String,
    val summary: String? = null,
    val kdoc: String? = null,
    val owned: Boolean = false,
    val ownedContainer: String? = null,
    val enumEntries: List<String> = emptyList(),
)

private data class TypeSignature(
    val header: String,
    val enumEntries: List<String>,
)

internal data class PresentationGroup(
    val name: String,
    val entries: List<Pair<String, String>>,
)

internal class ApiDocsException(
    message: String,
) : IllegalStateException(message)

private data class SourceUnit(
    val file: KtFile,
    val packageName: String,
    val relativePath: String,
)

internal class KotlinPsiApiExtractor : AutoCloseable {
    private val disposable: Disposable = Disposer.newDisposable("api-docs-generator")
    private val environment: KotlinCoreEnvironment

    init {
        val configuration =
            CompilerConfiguration().apply {
                put(CommonConfigurationKeys.MODULE_NAME, "api-docs-generator")
                put(CommonConfigurationKeys.MESSAGE_COLLECTOR_KEY, org.jetbrains.kotlin.cli.common.messages.MessageCollector.NONE)
            }
        environment =
            KotlinCoreEnvironment.createForProduction(
                disposable,
                configuration,
                EnvironmentConfigFiles.JVM_CONFIG_FILES,
            )
    }

    fun extract(sourceRoot: File): LinkedHashMap<String, ApiSymbol> {
        require(sourceRoot.isDirectory) { "Missing SDK source root: $sourceRoot" }
        val sources =
            sourceRoot
                .walkTopDown()
                .filter { it.isFile && it.extension == "kt" }
                .sortedBy { it.relativeTo(sourceRoot).invariantSeparatorsPath }
                .mapNotNull { sourceFile ->
                    val relativePath = sourceFile.relativeTo(sourceRoot).invariantSeparatorsPath
                    val ktFile = KtPsiFactory(environment.project, false).createFile(sourceFile.name, sourceFile.readText())
                    val parseErrors = PsiTreeUtil.findChildrenOfType(ktFile, PsiErrorElement::class.java)
                    if (parseErrors.isNotEmpty()) {
                        throw ApiDocsException(
                            "Kotlin parse errors in $relativePath:\n" +
                                parseErrors.joinToString("\n") { error ->
                                    "${error.errorDescription} at offset ${error.textOffset}"
                                },
                        )
                    }
                    val packageName = ktFile.packageFqName.asString()
                    val packageRelativePath =
                        relativePath
                            .removePrefix("java/")
                            .removePrefix("kotlin/")
                    val internalPath = packageRelativePath.startsWith("technology/polygon/omswallet/internal/")
                    val internalPackage =
                        packageName == "technology.polygon.omswallet.internal" ||
                            packageName.startsWith("technology.polygon.omswallet.internal.")
                    if (internalPath || internalPackage) {
                        if (!internalPath || !internalPackage) {
                            throw ApiDocsException(
                                "Internal source scope mismatch for $relativePath: package $packageName",
                            )
                        }
                        return@mapNotNull null
                    }
                    if (packageName != "technology.polygon.omswallet" &&
                        !packageName.startsWith("technology.polygon.omswallet.")
                    ) {
                        throw ApiDocsException("Unsupported public source package $packageName in $relativePath")
                    }
                    SourceUnit(ktFile, packageName, relativePath)
                }.toList()

        val validationErrors = mutableListOf<String>()
        sources.forEach { source ->
            validateDeclarations(
                declarations = source.file.declarations,
                ownerId = source.packageName,
                sourcePath = source.relativePath,
                errors = validationErrors,
            )
        }
        if (validationErrors.isNotEmpty()) {
            throw ApiDocsException(
                "Unsupported source-visible public declarations:\n${validationErrors.joinToString("\n")}",
            )
        }

        val symbols = linkedMapOf<String, ApiSymbol>()
        sources.forEach { source ->
            collectDeclarations(
                file = source.file,
                declarations = source.file.declarations,
                ownerId = source.packageName,
                aggregateInto = null,
                ownedContainer = null,
                symbols = symbols,
                sourcePath = source.relativePath,
            )
        }
        return symbols
    }

    private fun validateDeclarations(
        declarations: List<KtDeclaration>,
        ownerId: String,
        sourcePath: String,
        errors: MutableList<String>,
    ) {
        declarations.forEach { declaration ->
            if (!declaration.isSourceVisible()) return@forEach
            when (declaration) {
                is KtEnumEntry -> {
                    Unit
                }

                is KtObjectDeclaration -> {
                    val id = declaration.fqName?.asString() ?: "$ownerId.${declaration.name ?: "Companion"}"
                    validateDeclarations(declaration.declarations, id, sourcePath, errors)
                }

                is KtClass -> {
                    val id = declaration.fqName?.asString() ?: "$ownerId.${declaration.name}"
                    declaration.primaryConstructorParameters.forEach { parameter ->
                        validateExplicitType(parameter, id, sourcePath, errors)
                    }
                    if (declaration.isEnum()) {
                        declaration.declarations
                            .filterIsInstance<KtEnumEntry>()
                            .filter { it.body != null }
                            .forEach { entry -> errors += "Enum entry bodies are unsupported: $id#${entry.name} in $sourcePath" }
                    }
                    validateDeclarations(declaration.declarations, id, sourcePath, errors)
                }

                is KtNamedFunction -> {
                    val id = "$ownerId#${declaration.name}"
                    declaration.valueParameters.forEach { parameter ->
                        validateExplicitType(parameter, id, sourcePath, errors)
                    }
                    if (declaration.typeReference == null && !declaration.hasBlockBody()) {
                        errors += "Inferred public return type is unsupported: $id in $sourcePath"
                    }
                }

                is KtProperty -> {
                    val id = "$ownerId#${declaration.name}"
                    if (declaration.typeReference == null) {
                        errors += "Inferred public property type is unsupported: $id in $sourcePath"
                    }
                    if (declaration.hasModifier(KtTokens.CONST_KEYWORD) && declaration.initializer == null) {
                        errors += "Public const property has no initializer: $id in $sourcePath"
                    }
                }

                is KtSecondaryConstructor -> {
                    declaration.valueParameters.forEach { parameter ->
                        validateExplicitType(parameter, "$ownerId#constructor", sourcePath, errors)
                    }
                }

                is KtTypeAlias -> {
                    Unit
                }

                is KtClassInitializer -> {
                    Unit
                }

                is KtPrimaryConstructor -> {
                    Unit
                }

                else -> {
                    errors +=
                        "Unsupported public declaration ${declaration::class.simpleName} " +
                        "in $sourcePath at ${declaration.textOffset}"
                }
            }
        }
    }

    private fun validateExplicitType(
        parameter: KtParameter,
        ownerId: String,
        sourcePath: String,
        errors: MutableList<String>,
    ) {
        if (parameter.typeReference == null) {
            errors += "Inferred public parameter type is unsupported: $ownerId#${parameter.name} in $sourcePath"
        }
    }

    private fun collectDeclarations(
        file: KtFile,
        declarations: List<KtDeclaration>,
        ownerId: String,
        aggregateInto: String?,
        ownedContainer: String?,
        symbols: LinkedHashMap<String, ApiSymbol>,
        sourcePath: String,
    ) {
        declarations.forEach { declaration ->
            if (!declaration.isSourceVisible()) return@forEach
            when (declaration) {
                is KtEnumEntry -> {
                    Unit
                }

                is KtObjectDeclaration -> {
                    collectObject(file, declaration, ownerId, symbols, sourcePath)
                }

                is KtClass -> {
                    collectClass(file, declaration, symbols, sourcePath)
                }

                is KtNamedFunction -> {
                    addFunction(file, declaration, ownerId, aggregateInto, ownedContainer, symbols, sourcePath)
                }

                is KtProperty -> {
                    addProperty(file, declaration, ownerId, aggregateInto, ownedContainer, symbols, sourcePath)
                }

                is KtSecondaryConstructor -> {
                    addConstructor(file, declaration, ownerId, aggregateInto, ownedContainer, symbols, sourcePath)
                }

                is KtTypeAlias -> {
                    addTypeAlias(declaration, symbols, sourcePath)
                }

                is KtClassInitializer -> {
                    Unit
                }

                is KtPrimaryConstructor -> {
                    Unit
                }

                else -> {
                    throw ApiDocsException(
                        "Unsupported public declaration ${declaration::class.simpleName} in $sourcePath at ${declaration.textOffset}",
                    )
                }
            }
        }
    }

    private fun collectObject(
        file: KtFile,
        declaration: KtObjectDeclaration,
        ownerId: String,
        symbols: LinkedHashMap<String, ApiSymbol>,
        sourcePath: String,
    ) {
        val id = declaration.fqName?.asString() ?: "$ownerId.${declaration.name ?: "Companion"}"
        val typeSignature = classSignature(file, declaration)
        if (!declaration.isCompanion()) {
            addSymbol(
                symbols = symbols,
                id = id,
                signature = typeSignature.header,
                summary = declaration.summary(),
                sourcePath = sourcePath,
                enumEntries = typeSignature.enumEntries,
            )
        }
        val memberTarget =
            when {
                declaration.isCompanion() -> ownerId.takeUnless { it in splitMemberOwners }
                id in splitMemberOwners -> null
                else -> id
            }
        collectDeclarations(
            file,
            declaration.declarations,
            id,
            memberTarget,
            if (declaration.isCompanion()) typeSignature.header else null,
            symbols,
            sourcePath,
        )
    }

    private fun collectClass(
        file: KtFile,
        declaration: KtClass,
        symbols: LinkedHashMap<String, ApiSymbol>,
        sourcePath: String,
    ) {
        declaration.primaryConstructorParameters.forEach { parameter ->
            requireExplicitType(parameter, sourcePath)
        }
        val id =
            declaration.fqName?.asString()
                ?: throw ApiDocsException("Public class without a qualified name in $sourcePath at ${declaration.textOffset}")
        val typeSignature = classSignature(file, declaration)
        addSymbol(
            symbols = symbols,
            id = id,
            signature = typeSignature.header,
            summary = declaration.summary(),
            sourcePath = sourcePath,
            enumEntries = typeSignature.enumEntries,
        )
        val primaryConstructor = declaration.primaryConstructor
        if (primaryConstructor != null && !primaryConstructor.isSourceVisible()) {
            declaration.primaryConstructorParameters
                .filter { it.hasValOrVar() && it.isSourceVisible() }
                .forEach { parameter ->
                    val type =
                        parameter.typeReference
                            ?: throw ApiDocsException(
                                "Inferred public property type is unsupported: $id#${parameter.name} in $sourcePath",
                            )
                    addSymbol(
                        symbols,
                        id,
                        sourceSlice(file, parameter, type.textRange.endOffset),
                        parameter.summary(),
                        sourcePath,
                        kdoc = parameter.summaryKdoc(),
                        owned = true,
                    )
                }
        }
        val memberTarget = id.takeUnless { it in splitMemberOwners }
        collectDeclarations(file, declaration.declarations, id, memberTarget, null, symbols, sourcePath)
    }

    private fun addFunction(
        file: KtFile,
        declaration: KtNamedFunction,
        ownerId: String,
        aggregateInto: String?,
        ownedContainer: String?,
        symbols: LinkedHashMap<String, ApiSymbol>,
        sourcePath: String,
    ) {
        declaration.valueParameters.forEach { requireExplicitType(it, sourcePath) }
        if (declaration.typeReference == null && !declaration.hasBlockBody()) {
            throw ApiDocsException(
                "Inferred public return type is unsupported: $ownerId#${declaration.name} in $sourcePath",
            )
        }
        val name =
            declaration.name
                ?: throw ApiDocsException("Public function without a name in $sourcePath at ${declaration.textOffset}")
        val body = declaration.bodyExpression
        val end =
            when {
                body == null -> declaration.textRange.endOffset
                declaration.hasBlockBody() -> body.textRange.startOffset
                declaration.equalsToken != null -> declaration.equalsToken!!.textRange.startOffset
                else -> throw ApiDocsException("Unsupported function body shape for $ownerId#$name in $sourcePath")
            }
        addSymbol(
            symbols,
            aggregateInto ?: "$ownerId#$name",
            sourceSlice(file, declaration, end),
            declaration.summary(),
            sourcePath,
            kdoc = declaration.summaryKdoc(),
            owned = aggregateInto != null,
            ownedContainer = ownedContainer,
        )
    }

    private fun addProperty(
        file: KtFile,
        declaration: KtProperty,
        ownerId: String,
        aggregateInto: String?,
        ownedContainer: String?,
        symbols: LinkedHashMap<String, ApiSymbol>,
        sourcePath: String,
    ) {
        val name =
            declaration.name
                ?: throw ApiDocsException("Public property without a name in $sourcePath at ${declaration.textOffset}")
        val type =
            declaration.typeReference
                ?: throw ApiDocsException("Inferred public property type is unsupported: $ownerId#$name in $sourcePath")
        val end =
            if (declaration.hasModifier(KtTokens.CONST_KEYWORD)) {
                declaration.initializer?.textRange?.endOffset
                    ?: throw ApiDocsException("Public const property has no initializer: $ownerId#$name in $sourcePath")
            } else {
                type.textRange.endOffset
            }
        val signature =
            buildString {
                append(sourceSlice(file, declaration, end))
                declaration.nonPublicSetterVisibility()?.let { visibility ->
                    append("\n    $visibility set")
                }
            }
        addSymbol(
            symbols,
            aggregateInto ?: "$ownerId#$name",
            signature,
            declaration.summary(),
            sourcePath,
            kdoc = declaration.summaryKdoc(),
            owned = aggregateInto != null,
            ownedContainer = ownedContainer,
        )
    }

    private fun addConstructor(
        file: KtFile,
        declaration: KtSecondaryConstructor,
        ownerId: String,
        aggregateInto: String?,
        ownedContainer: String?,
        symbols: LinkedHashMap<String, ApiSymbol>,
        sourcePath: String,
    ) {
        declaration.valueParameters.forEach { requireExplicitType(it, sourcePath) }
        val parameterList =
            declaration.valueParameterList
                ?: throw ApiDocsException("Public constructor without parameters in $sourcePath at ${declaration.textOffset}")
        addSymbol(
            symbols,
            aggregateInto ?: "$ownerId#constructor",
            sourceSlice(file, declaration, parameterList.textRange.endOffset),
            declaration.summary(),
            sourcePath,
            kdoc = declaration.summaryKdoc(),
            owned = aggregateInto != null,
            ownedContainer = ownedContainer,
        )
    }

    private fun addTypeAlias(
        declaration: KtTypeAlias,
        symbols: LinkedHashMap<String, ApiSymbol>,
        sourcePath: String,
    ) {
        val id =
            declaration.fqName?.asString()
                ?: throw ApiDocsException("Public typealias without a qualified name in $sourcePath")
        addSymbol(symbols, id, declaration.text.trim(), declaration.summary(), sourcePath)
    }

    private fun addSymbol(
        symbols: LinkedHashMap<String, ApiSymbol>,
        id: String,
        signature: String,
        summary: String?,
        sourcePath: String,
        kdoc: String? = null,
        owned: Boolean = false,
        ownedContainer: String? = null,
        enumEntries: List<String> = emptyList(),
    ) {
        if ("technology.polygon.omswallet.internal" in signature ||
            "technology.polygon.omswallet.internal.generated" in signature
        ) {
            throw ApiDocsException("Internal type leaked into public signature $id in $sourcePath")
        }
        val symbol = symbols.getOrPut(id) { ApiSymbol(id) }
        if (symbol.declarations.none { it.signature == signature }) {
            symbol.declarations += ApiDeclaration(signature, summary, kdoc, owned, ownedContainer, enumEntries)
        }
    }

    private fun classSignature(
        file: KtFile,
        declaration: KtClassOrObject,
    ): TypeSignature {
        val bodyStart =
            declaration.body
                ?.lBrace
                ?.textRange
                ?.startOffset ?: declaration.textRange.endOffset
        val start = declaration.signatureStart()
        var signature = file.text.substring(start, bodyStart)
        val replacements = mutableListOf<SourceReplacement>()
        val constructor = (declaration as? KtClass)?.primaryConstructor
        if (constructor != null && !constructor.isSourceVisible()) {
            replacements += SourceReplacement(constructor.textRange.startOffset, constructor.textRange.endOffset, "")
        }
        declaration.superTypeListEntries.filterIsInstance<KtSuperTypeCallEntry>().forEach { entry ->
            val type =
                entry.typeReference
                    ?: throw ApiDocsException("Super constructor call without a type in ${declaration.fqName}")
            replacements += SourceReplacement(entry.textRange.startOffset, entry.textRange.endOffset, type.text)
        }
        replacements.sortedByDescending { it.startOffset }.forEach { replacement ->
            if (replacement.startOffset < start || replacement.endOffset > bodyStart) {
                throw ApiDocsException("Signature replacement outside ${declaration.fqName}")
            }
            signature =
                signature.replaceRange(
                    replacement.startOffset - start,
                    replacement.endOffset - start,
                    replacement.text,
                )
        }
        val enumEntries =
            if (declaration is KtClass && declaration.isEnum()) {
                declaration.declarations.filterIsInstance<KtEnumEntry>().map { entry ->
                    if (entry.body != null) {
                        throw ApiDocsException("Enum entry bodies are unsupported: ${declaration.fqName}#${entry.name}")
                    }
                    val delimiterOffset =
                        listOfNotNull(
                            entry.node
                                .findChildByType(KtTokens.COMMA)
                                ?.textRange
                                ?.startOffset,
                            entry.node
                                .findChildByType(KtTokens.SEMICOLON)
                                ?.textRange
                                ?.startOffset,
                        ).minOrNull()
                    val end = delimiterOffset ?: entry.textRange.endOffset
                    listOfNotNull(entry.summaryKdoc(), sourceSlice(file, entry, end)).joinToString("\n")
                }
            } else {
                emptyList()
            }
        val header = declaration.replaceLinks(normalizeSourceText(file, start, signature).trim())
        return TypeSignature(header, enumEntries)
    }

    private fun sourceSlice(
        file: KtFile,
        declaration: KtDeclaration,
        endOffset: Int,
    ): String {
        val start = declaration.signatureStart()
        val signature = normalizeSourceText(file, start, file.text.substring(start, endOffset)).trim()
        return declaration.replaceLinks(signature)
    }

    private fun normalizeSourceText(
        file: KtFile,
        startOffset: Int,
        text: String,
    ): String {
        val lineStart = file.text.lastIndexOf('\n', startOffset - 1) + 1
        val sourceIndent =
            file.text
                .substring(lineStart, startOffset)
                .takeIf { it.isBlank() }
                .orEmpty()
        return text
            .lineSequence()
            .mapIndexed { index, line -> if (index == 0) line else line.removePrefix(sourceIndent) }
            .joinToString("\n")
    }

    private fun KtDeclaration.signatureStart(): Int {
        val docEnd = docComment?.textRange?.endOffset ?: return textRange.startOffset
        var start = docEnd
        val fileText = containingKtFile.text
        while (start < textRange.endOffset && fileText[start].isWhitespace()) start++
        return start
    }

    private fun requireExplicitType(
        parameter: KtParameter,
        sourcePath: String,
    ) {
        if (parameter.typeReference == null) {
            throw ApiDocsException(
                "Inferred public parameter type is unsupported: ${parameter.name} in $sourcePath at ${parameter.textOffset}",
            )
        }
    }

    private fun KtDeclaration.isSourceVisible(): Boolean =
        !hasModifier(KtTokens.PRIVATE_KEYWORD) &&
            !hasModifier(KtTokens.INTERNAL_KEYWORD) &&
            !hasModifier(KtTokens.PROTECTED_KEYWORD)

    private fun KtProperty.nonPublicSetterVisibility(): String? {
        val setter = setter ?: return null
        return when {
            setter.hasModifier(KtTokens.PRIVATE_KEYWORD) -> "private"
            setter.hasModifier(KtTokens.INTERNAL_KEYWORD) -> "internal"
            setter.hasModifier(KtTokens.PROTECTED_KEYWORD) -> "protected"
            else -> null
        }
    }

    private fun KtNamedDeclaration.summary(): String? =
        (docComment as? KDoc)
            ?.getDefaultSection()
            ?.getContent()
            ?.trim()
            ?.lineSequence()
            ?.takeWhile { it.isNotBlank() }
            ?.joinToString("\n")
            ?.let { summary -> (docComment as KDoc).replaceLinks(summary) }
            ?.takeIf { it.isNotBlank() }

    private fun KtNamedDeclaration.summaryKdoc(): String? =
        summary()?.let { summary ->
            buildString {
                appendLine("/**")
                summary.lineSequence().forEach { line -> appendLine(" * $line") }
                append(" */")
            }
        }

    private fun KDoc.replaceLinks(text: String): String = replaceLinks(text, PsiTreeUtil.findChildrenOfType(this, KDocLink::class.java))

    private fun KtDeclaration.replaceLinks(text: String): String =
        replaceLinks(text, PsiTreeUtil.findChildrenOfType(this, KDocLink::class.java))

    private fun replaceLinks(
        text: String,
        links: Collection<KDocLink>,
    ): String =
        links
            .filter { link ->
                link.getTagIfSubject() == null && link.text.startsWith("[") && link.text.endsWith("]")
            }.fold(text) { rendered, link -> rendered.replace(link.text, "`${link.getLinkText()}`") }

    override fun close() {
        Disposer.dispose(disposable)
    }
}

private data class SourceReplacement(
    val startOffset: Int,
    val endOffset: Int,
    val text: String,
)

internal fun parsePresentationConfig(file: File): List<PresentationGroup> {
    val groups = mutableListOf<PresentationGroup>()
    var groupName: String? = null
    var entries = mutableListOf<Pair<String, String>>()

    fun finishGroup() {
        groupName?.let { groups += PresentationGroup(it, entries.toList()) }
        entries = mutableListOf()
    }

    file.forEachLine { rawLine ->
        val line = rawLine.trim()
        when {
            line.isEmpty() || line.startsWith("#") -> {
                Unit
            }

            line.startsWith("[") && line.endsWith("]") -> {
                finishGroup()
                groupName = line.removePrefix("[").removeSuffix("]").trim()
            }

            else -> {
                if (groupName == null || '=' !in line) {
                    throw ApiDocsException("Invalid presentation config line: $rawLine")
                }
                val id = line.substringBefore('=').trim()
                val label = line.substringAfter('=').trim()
                if (id.isEmpty() || label.isEmpty()) {
                    throw ApiDocsException("Presentation entries require a symbol ID and label: $rawLine")
                }
                entries += id to label
            }
        }
    }
    finishGroup()
    if (groups.map { it.name } != requiredGroups) {
        throw ApiDocsException("Presentation groups must be exactly: ${requiredGroups.joinToString()}")
    }
    return groups
}

internal fun renderApiDocs(
    symbols: Map<String, ApiSymbol>,
    groups: List<PresentationGroup>,
): String {
    val configured = groups.flatMap { it.entries }.map { it.first }
    val duplicates =
        configured
            .groupingBy { it }
            .eachCount()
            .filterValues { it > 1 }
            .keys
    if (duplicates.isNotEmpty()) {
        throw ApiDocsException("Duplicate configured symbols: ${duplicates.sorted().joinToString()}")
    }
    val missing = configured.toSet() - symbols.keys
    if (missing.isNotEmpty()) {
        throw ApiDocsException("Configured public symbols are missing:\n${missing.sorted().joinToString("\n")}")
    }
    val unassigned = symbols.keys - configured.toSet()
    if (unassigned.isNotEmpty()) {
        throw ApiDocsException("Source-visible public symbols are unassigned:\n${unassigned.joinToString("\n")}")
    }

    return buildString {
        appendLine(GENERATED_MARKER)
        appendLine()
        appendLine("# Kotlin API reference")
        groups.forEach { group ->
            appendLine()
            appendLine("## ${group.name}")
            group.entries.forEach { (id, label) ->
                val symbol = symbols.getValue(id)
                appendLine()
                appendLine("### `$label`")
                val anchor =
                    symbol.declarations.firstOrNull { !it.owned }
                        ?: throw ApiDocsException("Public symbol has no anchor declaration: ${symbol.id}")
                sharedSummary(symbol)?.let { summary ->
                    appendLine()
                    appendLine(summary)
                }
                appendLine()
                appendLine("```kotlin")
                appendLine(renderSymbolDeclaration(symbol, anchor))
                appendLine("```")
            }
        }
    }
}

private fun sharedSummary(symbol: ApiSymbol): String? {
    val anchorSummaries = symbol.declarations.filter { !it.owned }.map { it.summary }
    if (anchorSummaries.size > 1 && anchorSummaries.distinct().size > 1) {
        throw ApiDocsException(
            "Public overloads for ${symbol.id} have inconsistent summaries. " +
                "Use the same first KDoc paragraph for every overload or configure separate API entries.",
        )
    }
    return anchorSummaries.firstOrNull()
}

private fun renderSymbolDeclaration(
    symbol: ApiSymbol,
    anchor: ApiDeclaration,
): String {
    val ownedMembers = symbol.declarations.filter { it.owned }
    if (ownedMembers.isEmpty() && anchor.enumEntries.isEmpty()) {
        return symbol.declarations.joinToString("\n\n") { it.signature }
    }
    val extraAnchors = symbol.declarations.filter { !it.owned && it !== anchor }
    if (extraAnchors.isNotEmpty()) {
        throw ApiDocsException("Compound public symbol has multiple anchor declarations: ${symbol.id}")
    }

    return buildString {
        appendLine("${anchor.signature} {")
        if (anchor.enumEntries.isNotEmpty()) {
            anchor.enumEntries.forEachIndexed { index, entry ->
                append(entry.prependIndent("    "))
                val isLast = index == anchor.enumEntries.lastIndex
                appendLine(if (isLast && ownedMembers.isNotEmpty()) ";" else ",")
            }
        }
        if (ownedMembers.isNotEmpty()) {
            if (anchor.enumEntries.isNotEmpty()) appendLine()
            appendLine(renderOwnedMembers(ownedMembers))
        }
        append("}")
    }
}

private fun renderOwnedMembers(members: List<ApiDeclaration>): String =
    buildString {
        var index = 0
        var firstBlock = true
        while (index < members.size) {
            if (!firstBlock) {
                appendLine()
                appendLine()
            }
            firstBlock = false
            val container = members[index].ownedContainer
            if (container == null) {
                val member = members[index]
                member.kdoc?.let { appendLine(it.prependIndent("    ")) }
                append(member.signature.prependIndent("    "))
                index++
                continue
            }

            val end = (index + 1 until members.size).firstOrNull { members[it].ownedContainer != container } ?: members.size
            appendLine("    $container {")
            members.subList(index, end).forEachIndexed { memberIndex, member ->
                if (memberIndex > 0) {
                    appendLine()
                    appendLine()
                }
                member.kdoc?.let { appendLine(it.prependIndent("        ")) }
                append(member.signature.prependIndent("        "))
            }
            appendLine()
            append("    }")
            index = end
        }
    }

fun main(args: Array<String>) {
    require(args.size == 4) {
        "Usage: ApiDocsGeneratorKt <list|generate|check> <source-root> <presentation-config> <docs-output>"
    }
    val mode = args[0]
    val sourceRoot = File(args[1])
    val configFile = File(args[2])
    val outputFile = File(args[3])

    KotlinPsiApiExtractor().use { extractor ->
        val symbols = extractor.extract(sourceRoot)
        if (mode == "list") {
            symbols.values.forEach { symbol ->
                println("${symbol.id} = ${symbol.id.substringAfterLast('.').substringAfterLast('#')}")
            }
            return
        }
        val rendered = renderApiDocs(symbols, parsePresentationConfig(configFile))
        when (mode) {
            "generate" -> {
                outputFile.writeText(rendered)
            }

            "check" -> {
                if (!outputFile.isFile || outputFile.readText() != rendered) {
                    throw ApiDocsException("docs/api.md is stale. Run ./gradlew generateApiDocs.")
                }
            }

            else -> {
                throw ApiDocsException("Unknown mode: $mode")
            }
        }
    }
}
